export const TripObjectStructure = {
  _id: "",
  id: "",
  tripId: "",
  transporter: "",
  tripStartTime: "",
  currentStatusCode: "CS",
  currenStatus: "Coming Soon",
  phoneNumber: "",
  etaDays: 0,
  distanceRemaining: 0,
  tripEndTime: "",
  source: "",
  sourceLatitude: "",
  sourceLongitude: "",
  dest: "",
  destLatitude: "",
  destLongitude: "",
  lastPingTime: "",
  createdAt: "",
  tat: "Others",
};
